BITCOIN = {
    :network => :bitcoin,
    :listen => ["0.0.0.0", nil],
    :connect => [],
    :command => ["127.0.0.1", 9999],
    :storage => "utxo::sqlite://~/.bitcoin-ruby/<network>/blocks.db",
    :announce => false,
    :external_port => nil,
    :mode => :full,
    :cache_head => true,
    :index_nhash => false,
    :index_p2sh_type => false,
    :dns => true,
    :epoll_limit => 10000,
    :epoll_user => nil,
    :addr_file => "~/.bitcoin-ruby/<network>/peers.json",
    :log => {
        :network => :error,
        :storage => :error,
    },
    :max => {
        :connections_out => 8,
        :connections_in => 32,
        :connections => 8,
        :addr => 256,
        :queue => 501,
        :inv => 501,
        :inv_cache => 0,
        :unconfirmed => 100,
    },
    :intervals => {
        :queue => 1,
        :inv_queue => 1,
        :addrs => 5,
        :connect => 5,
        :relay => 0,
    },
    :import => nil,
    :skip_validation => false,
    :check_blocks => 1000,
}
